language: ruby
os: osx
env: OSX=10.12
osx_image: xcode8.1
rvm: system

before_install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOMEBREW_REPOSITORY="$(brew --repo)"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  - git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master
  - brew update || brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

install:
  - brew install mysql

script:
  - brew style "$TRAVIS_REPO_SLUG"
  # Test start command
  - brew services start mysql
  - brew services list | grep mysql
  - sleep 5
  - mysql -uroot -e 'show databases'
  # Test stop command
  - brew services stop mysql
  - sleep 5
  - test ! `launchctl list | grep mysql`
  # Test run command
  - brew services run mysql
  - sleep 5
  - mysql -uroot -e 'show databases'
  - brew services stop mysql

notifications:
  email:
    on_success: never
    on_failure: always
